### ISSUE TITLE
Implement a remove a product functionality from order list items

### ISSUE THREAD

**Issue by ahayder** [mauchchhash/simplePOS#1]
When a user creating an order..... he/she should able to remove an item from the order list before creating the order.
![image](https://user-images.githubusercontent.com/2572383/66736943-7064d800-ee8c-11e9-93f7-3892b5091841.png)

**Comment by mauchchhash** [comment]
Working on it..

**Comment by ahayder** [comment]
@mauchchhash any update?

**Comment by mauchchhash** [comment]
Well, I am getting a limited amount of time after office everyday. But I am trying to fix the issues as fast as I can..

**Comment by ahayder** [comment]
Ok bro. Have you seen other issues?

**Comment by mauchchhash** [comment]
Yes I have. Will work on them as soon as I can.

**Comment by ahayder** [comment]
Please deploy an update if you solve the issue. And feel free to close issue if you solve any. Just leave a comment and close the issue.

**Comment by mauchchhash** [comment]
Fixed the Issue. Closing the issue...
