### ISSUE TITLE
Design issues in the order list section

### ISSUE THREAD

**Issue by ahayder** [mauchchhash/simplePOS#5]
Please find a way to modify the input box CSS styles so that we can make the section more professional. If you find a way then inform me here by commenting.
<img width="367" alt="Screenshot 2019-10-15 at 11 41 40" src="https://user-images.githubusercontent.com/2572383/66803364-3275bb80-ef41-11e9-8f51-9c9da9e6d593.png">

**Comment by mauchchhash** [comment]
Please close the issue if you are content with the changes..

**Comment by ahayder** [comment]
cool
